/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Body
import io.swagger.client.model.Inline_response_200
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ResourceProvidersApi {

  /**
   * Create a new resource provider.
   * 
   * Expected answers:
   *   code 201 :  (successful operation)
   *   code 409 :  (another resource provider exists with the provided name or uuid)
   * 
   * Available security schemes:
   *   api_key (apiKey)
   * 
   * @param body order placed for purchasing the pet
   */
  def createResourceProvider(body: Body)(implicit apiKey: ApiKeyValue): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost:9000/placement", "/resource_providers", "application/json")
      .withApiKey(apiKey, "x-auth-token", HEADER)
      .withBody(body)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](409)
        /**
   * List an optionally filtered collection of resource providers
   * 
   * Expected answers:
   *   code 200 : Inline_response_200 (successful operation)
   * 
   * Available security schemes:
   *   api_key (apiKey)
   * 
   * @param resourcesQuery A comma-separated list of strings indicating an amount of resource of a specified class that a provider must have the capacity to serve:: resources&#x3D;VCPU:4,DISK_GB:64,MEMORY_MB:2048
   * @param memberOf A comma-separated list of strings representing aggregate uuids. The returned resource providers must be associated with at least one of the aggregates identified by uuid.
   * @param uuid The uuid of a resource provider.
   * @param name The name of a resource provider.
   */
  def showResourceProviders(resourcesQuery: Option[String] = None, memberOf: Option[String] = None, uuid: Option[String] = None, name: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[Inline_response_200] =
    ApiRequest[Inline_response_200](ApiMethods.GET, "https://localhost:9000/placement", "/resource_providers", "application/json")
      .withApiKey(apiKey, "x-auth-token", HEADER)
      .withQueryParam("resources_query", resourcesQuery)
      .withQueryParam("member_of", memberOf)
      .withQueryParam("uuid", uuid)
      .withQueryParam("name", name)
      .withSuccessResponse[Inline_response_200](200)
      

}

